name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
          username: "aswar"
          host: "103.171.84.140"
          password: "Sembarang123"
          script: 'cd /var/www/html/MerqataAPI && ./deployer.sh'
      
