name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
          username: "aswar"
          host: "103.171.84.140"
          password: "Sembarang123"
          script: 'cd /var/www/edelivery.my.id && ./deployer.sh'
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
